replicaCount: 2
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: hello-stage.local
      paths:
        - path: /
          pathType: Prefix
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m" 