apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-nginx-stage
  namespace: argocd
spec:
  project: teama-stage
  source:
    repoURL: https://github.com/GenjiM1n4moto/argocd-bootstrap-example.git
    targetRevision: staging
    path: charts/hello-nginx
    helm:
      valueFiles:
        - values.yaml
        - environments/stage/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
