apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: teama-prod
  namespace: argocd
spec:
  description: Team A Production Environment
  sourceRepos:
    - '*'
  destinations:
    - namespace: prod
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*' 