replicaCount: 1
image:
  repository: nginx
  tag: 1.27-alpine
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  className: ""
  hosts:
    - host: hello.local
      paths:
        - path: /
          pathType: Prefix
resources: {}
