apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-nginx.fullname" . }}
  labels: {{- include "hello-nginx.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "hello-nginx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "hello-nginx.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
