replicaCount: 1
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: hello-dev.local
      paths:
        - path: /
          pathType: Prefix
resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m" 